---
- name: Install and configure k3s master
  hosts: masters
  become: true
  tasks:
    - name: Ensure firewalld is installed and running
      dnf:
        name: firewalld
        state: present
    - service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open firewall ports for k3s master
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 6443/tcp    # Kubernetes API
        - 2379-2380/tcp # etcd
        - 10250/tcp   # kubelet
        - 10251/tcp   # kube-scheduler
        - 10252/tcp   # kube-controller-manager
        - 30000-32767/tcp # NodePort range

    - name: Download and install k3s master
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get k3s node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set fact for node token
      set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"

    - name: Save k3s token to local file
      local_action:
        module: copy
        content: "{{ k3s_token }}"
        dest: ./k3s_node_token.txt

    - name: Save master IP for agents
      local_action:
        module: copy
        content: "{{ hostvars[inventory_hostname].ansible_host }}"
        dest: ./k3s_master_ip.txt


- name: Install and configure k3s agents
  hosts: agents
  become: true
  vars:
    master_ip: "{{ lookup('file', './k3s_master_ip.txt') }}"
    join_token: "{{ lookup('file', './k3s_node_token.txt') }}"
  tasks:
    - name: Ensure firewalld is installed and running
      dnf:
        name: firewalld
        state: present
    - service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open firewall ports for k3s agents
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 10250/tcp
        - 30000-32767/tcp

    - name: Download and install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ join_token }} sh -
      args:
        creates: /usr/local/bin/k3s-agent
